FROM golang:1.13.11-alpine3.11 as builder

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY server.go ./

RUN go build -o /build/bin/server server.go

FROM alpine:3.11

RUN apk add --update lsof vim

COPY --from=builder /build/bin/server /usr/bin/debug-server
CMD ["/usr/bin/debug-server", "80"]
